[ADD] Weblate Widget
OCA/oca-addons-repo-template pull request #5
Opened 2020-08-18 09:30 UTC by rousseldenis

2020-08-18 09:30 UTC, rousseldenis commented
I haven't tested macro. If anyone can check this.

@sbidoul @pedrobaeza 

Following this : https://github.com/OCA/stock-logistics-warehouse/pull/950

2020-08-19 07:47 UTC, Yajo requested changes
Add a test please.

2020-08-20 14:08 UTC, rousseldenis commented
> Add a test please.

Arf, didn't there was some for that !

Ok

2020-08-20 14:24 UTC, rousseldenis commented
@Yajo Done and :green_apple:

2020-08-31 09:02 UTC, Yajo reviewed
I suggest a small enhancement before merging.

2020-08-31 09:02 UTC, Yajo commented on README.md.jinja
> +{%- macro odoo_version_tr(version) -%}
```suggestion
{%- macro odoo_version_slug(version) -%}
```

This macro name is more explicit IMHO.

2020-08-31 09:02 UTC, Yajo commented on README.md.jinja
> +[![Translation Status](https://translation.odoo-community.org/widgets/{{ repo_slug }}-{{ odoo_version_tr(odoo_version) }}/-/svg-badge.svg)](https://translation.odoo-community.org/engage/{{ repo_slug
```suggestion
[![Translation Status](https://translation.odoo-community.org/widgets/{{ repo_slug }}-{{ odoo_version_slug(odoo_version) }}/-/svg-badge.svg)](https://translation.odoo-community.org/engage/{{ repo_slug }}-{{ odoo_version_slug(odoo_version) }}/?utm_source=widget)
```

2020-09-22 14:07 UTC, rousseldenis commented
@Yajo changes done. @sbidoul This could be added before 14.0 branches creation ?

2020-09-23 08:13 UTC, Yajo approved these changes

2020-09-23 08:19 UTC, Yajo commented
@sbidoul wanna merge?

2020-09-23 09:39 UTC, merged